// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
import type { HolonicBraidModule } from './src/modules/HolonicBraid';
import type { HolonicMemoryModule } from './src/modules/HolonicMemory';
import type { ImagesModule } from './src/modules/Images';
import type { OrchestratorModule } from './src/modules/Orchestrator';
import type { ReasoningNetworkModule } from './src/modules/ReasoningNetwork';

export type { OASISResponse, OASISSession };

// ── Shared request/response shapes ──────────────────────────────────────────

export interface ChatMessage {
  /** "system" | "user" | "assistant" */
  Role: string;
  Content: string;
}

export interface RoutingOptions {
  /**
   * Cost / latency / quality priority hint for provider selection.
   * @default "cost"
   */
  Priority?: string;
  /**
   * Automatically fail over to the next-best provider on error/timeout.
   * @default true
   */
  Fallback?: boolean;
  /**
   * Per-request OpenServ gateway override.
   * null/omit = use OASIS_DNA.Web6.PreferOpenServ default.
   * true  = route through OpenServ regardless of provider.
   * false = call the named provider directly even if PreferOpenServ is on.
   * Only applies when Provider is "auto".
   */
  UseOpenServ?: boolean | null;
}

export interface CompletionRequest {
  /**
   * Target provider: "auto" | "openai" | "anthropic" | "gemini" | "groq" |
   * "mistral" | "cohere" | "xai" | "deepseek" | "huggingface" | "azureopenai" |
   * "awsbedrock" | "openserv" | "ollama".
   * "auto" lets WEB6 pick the best available configured provider.
   * @default "auto"
   */
  Provider?: string;
  /**
   * Model id (e.g. "gpt-4o", "claude-opus-4-8") or "auto".
   * @default "auto"
   */
  Model?: string;
  Messages: ChatMessage[];
  Routing?: RoutingOptions;
  /** Optional OASIS avatar id for WEB4 identity / karma grounding. */
  AvatarId?: string;
  Temperature?: number;
  MaxTokens?: number;
  /**
   * Per-request FAHRN override.
   * null/omit = use OASIS_DNA.Web6.EnableFAHRN.
   * When true, WEB6 dispatches the last user message through the FAHRN
   * reasoning network and injects the Mermaid execution plan into the
   * system context before calling the provider.
   */
  UseFAHRN?: boolean | null;
  /**
   * Per-request Holonic BRAID override.
   * null/omit = use OASIS_DNA.Web6.EnableHolonicBraid.
   * When true, WEB6 fetches the shared reasoning graph for FahrnTaskType
   * and injects it into the system context before calling the provider.
   */
  UseHolonicBraid?: boolean | null;
  /**
   * Task type used for FAHRN scoring and Holonic BRAID graph look-up.
   * e.g. "general" | "legal" | "code" | "mathematics" | "trust-guidance"
   * @default "general"
   */
  FahrnTaskType?: string;
}

export interface CompletionResponse {
  Content: string;
  Provider: string;
  Model: string;
  InputTokens?: number;
  OutputTokens?: number;
}

// ── CompletionModule (typed) ─────────────────────────────────────────────────

export declare class CompletionModule {
  complete(args: CompletionRequest): Promise<OASISResponse<CompletionResponse>>;
  openServModels(): Promise<OASISResponse<unknown[]>>;
}

export interface Web6ClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class Web6Client {
  constructor(options?: Web6ClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
  readonly completion: CompletionModule;
  readonly holonicBraid: HolonicBraidModule;
  readonly holonicMemory: HolonicMemoryModule;
  readonly images: ImagesModule;
  readonly orchestrator: OrchestratorModule;
  readonly reasoningNetwork: ReasoningNetworkModule;
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
}

export default Web6Client;
