// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
import type { CompletionModule } from './src/modules/Completion';
import type { HolonicBraidModule } from './src/modules/HolonicBraid';
import type { HolonicMemoryModule } from './src/modules/HolonicMemory';
import type { ImagesModule } from './src/modules/Images';
import type { OrchestratorModule } from './src/modules/Orchestrator';
import type { ReasoningNetworkModule } from './src/modules/ReasoningNetwork';

export type { OASISResponse, OASISSession };

export interface Web6ClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class Web6Client {
  constructor(options?: Web6ClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
  readonly completion: CompletionModule;
  readonly holonicBraid: HolonicBraidModule;
  readonly holonicMemory: HolonicMemoryModule;
  readonly images: ImagesModule;
  readonly orchestrator: OrchestratorModule;
  readonly reasoningNetwork: ReasoningNetworkModule;
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
}

export default Web6Client;
