// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class A2AModule {
  constructor(http: unknown);

  /** POST a2a/tasks/{id}/cancel */
  cancelTask(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET a2a/tasks/{id} */
  getTask(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST a2a/tasks/send */
  sendTask(args?: Record<string, any>): Promise<OASISResponse>;
}
