'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1 (source: WEB6 AI Layer WebAPI CompletionController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CompletionModule {
  constructor(http) {
    this._http = http;

    // post v1/complete
    this.complete = makeOperation(http, "v1", "POST", "complete");
    // get v1/openserv/models
    this.openServModels = makeOperation(http, "v1", "GET", "openserv/models");
  }
}

module.exports = { CompletionModule };
