// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CompletionModule {
  constructor(http: unknown);

  /** POST v1/complete */
  complete(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/embed */
  embed(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/openserv/models */
  openServModels(args?: Record<string, any>): Promise<OASISResponse>;
}
