// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class DidModule {
  constructor(http: unknown);

  /** POST v1/auth/did */
  createDid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/auth/vc */
  issueVc(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/auth/did/{did} */
  resolveDid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/auth/vc/verify */
  verifyVc(args?: Record<string, any>): Promise<OASISResponse>;
}
