'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/auth (source: WEB6 AI Layer WebAPI DidController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class DidModule {
  constructor(http) {
    this._http = http;

    // POST v1/auth/did
    this.createDid = makeOperation(http, "v1/auth", "POST", "did");
    // POST v1/auth/vc
    this.issueVc = makeOperation(http, "v1/auth", "POST", "vc");
    // GET v1/auth/did/{did}
    this.resolveDid = makeOperation(http, "v1/auth", "GET", "did/{did}");
    // POST v1/auth/vc/verify
    this.verifyVc = makeOperation(http, "v1/auth", "POST", "vc/verify");
  }
}

module.exports = { DidModule };
