// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ExternalMemoryModule {
  constructor(http: unknown);

  /** POST v1/memory/external/add */
  add(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE v1/memory/external/{provider}/{id} */
  delete(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/memory/external/providers */
  getProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/memory/external/search */
  search(args?: Record<string, any>): Promise<OASISResponse>;
}
