'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/memory/external (source: WEB6 AI Layer WebAPI ExternalMemoryController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ExternalMemoryModule {
  constructor(http) {
    this._http = http;

    // POST v1/memory/external/add
    this.add = makeOperation(http, "v1/memory/external", "POST", "add");
    // DELETE v1/memory/external/{provider}/{id}
    this.delete = makeOperation(http, "v1/memory/external", "DELETE", "{provider}/{id}");
    // GET v1/memory/external/providers
    this.getProviders = makeOperation(http, "v1/memory/external", "GET", "providers");
    // POST v1/memory/external/search
    this.search = makeOperation(http, "v1/memory/external", "POST", "search");
  }
}

module.exports = { ExternalMemoryModule };
