// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class FahrnSolveModule {
  constructor(http: unknown);

  /** GET v1/fahrn/budget-estimate */
  budgetEstimate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/fahrn/solve */
  solve(args?: Record<string, any>): Promise<OASISResponse>;
}
