'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/fahrn (source: WEB6 AI Layer WebAPI FahrnSolveController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class FahrnSolveModule {
  constructor(http) {
    this._http = http;

    // GET v1/fahrn/budget-estimate
    this.budgetEstimate = makeOperation(http, "v1/fahrn", "GET", "budget-estimate");
    // POST v1/fahrn/solve
    this.solve = makeOperation(http, "v1/fahrn", "POST", "solve");
  }
}

module.exports = { FahrnSolveModule };
