'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/health (source: WEB6 AI Layer WebAPI HealthController.cs).
 * Unauthenticated liveness / readiness probe. Returns { status: "ok" | "degraded" }.
 */
class HealthModule {
  constructor(http) {
    this._http = http;

    // GET v1/health
    this.check = makeOperation(http, "v1", "GET", "health");
  }
}

module.exports = { HealthModule };
