// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HolonicMemoryModule {
  constructor(http: unknown);

  /** GET v1/holonic-memory/earth */
  getEarthHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/holonic-memory/holons/{childHolonId}/propagate */
  propagate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/holonic-memory/holons/{holonId}/memory */
  recordMemory(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT v1/holonic-memory/holons/{holonId}/membrane-rule */
  setMembraneRule(args?: Record<string, any>): Promise<OASISResponse>;
}
