'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/holonic-braid (source: WEB6 AI Layer WebAPI HolonicBraidController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonicBraidModule {
  constructor(http) {
    this._http = http;

    // get v1/holonic-braid/graph/{taskType}
    this.getGraph = makeOperation(http, "v1/holonic-braid", "GET", "graph/{taskType}");
    // post v1/holonic-braid/graph/{taskType}
    this.saveGraph = makeOperation(http, "v1/holonic-braid", "POST", "graph/{taskType}");
  }
}

module.exports = { HolonicBraidModule };
