// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HolonicBraidModule {
  constructor(http: unknown);

  /** GET v1/holonic-braid/graph/{taskType} */
  getGraph(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/holonic-braid/graph/{taskType} */
  saveGraph(args?: Record<string, any>): Promise<OASISResponse>;
}
