'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/holonic-memory (source: WEB6 AI Layer WebAPI HolonicMemoryController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonicMemoryModule {
  constructor(http) {
    this._http = http;

    // GET v1/holonic-memory/earth
    this.getEarthHolon = makeOperation(http, "v1/holonic-memory", "GET", "earth");
    // POST v1/holonic-memory/holons (query: level, name, parentHolonId)
    this.getOrCreateHolon = makeOperation(http, "v1/holonic-memory", "POST", "holons", {"query":["level","name","parentHolonId"]});
    // POST v1/holonic-memory/holons/{childHolonId}/propagate
    this.propagate = makeOperation(http, "v1/holonic-memory", "POST", "holons/{childHolonId}/propagate");
    // POST v1/holonic-memory/holons/{childHolonId}/propagate-up
    this.propagateUp = makeOperation(http, "v1/holonic-memory", "POST", "holons/{childHolonId}/propagate-up");
    // POST v1/holonic-memory/holons/{holonId}/memory
    this.recordMemory = makeOperation(http, "v1/holonic-memory", "POST", "holons/{holonId}/memory");
    // GET v1/holonic-memory/holons/{holonId}/memory/search
    this.searchMemory = makeOperation(http, "v1/holonic-memory", "GET", "holons/{holonId}/memory/search");
    // PUT v1/holonic-memory/holons/{holonId}/membrane-rule
    this.setMembraneRule = makeOperation(http, "v1/holonic-memory", "PUT", "holons/{holonId}/membrane-rule");
  }
}

module.exports = { HolonicMemoryModule };
