// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ImagesModule {
  constructor(http: unknown);

  /** POST v1/images/generate */
  generate(args?: Record<string, any>): Promise<OASISResponse>;
}
