'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/images (source: WEB6 AI Layer WebAPI ImagesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ImagesModule {
  constructor(http) {
    this._http = http;

    // POST v1/images/generate
    this.generate = makeOperation(http, "v1/images", "POST", "generate");
  }
}

module.exports = { ImagesModule };
