'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { CompletionModule } = require('./Completion');
const { FahrnSolveModule } = require('./FahrnSolve');
const { HolonicBraidModule } = require('./HolonicBraid');
const { HolonicMemoryModule } = require('./HolonicMemory');
const { ImagesModule } = require('./Images');
const { OrchestratorModule } = require('./Orchestrator');
const { ReasoningNetworkModule } = require('./ReasoningNetwork');
const { DidModule } = require('./Did');
const { ExternalMemoryModule } = require('./ExternalMemory');
const { MLNetModule } = require('./MLNet');
const { TelemetryModule } = require('./Telemetry');
const { UsageModule } = require('./Usage');
const { ProvidersModule } = require('./Providers');
const { A2AModule } = require('./A2A');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.completion = client.completion || new CompletionModule(http);
  client.fahrnSolve = client.fahrnSolve || new FahrnSolveModule(http);
  client.holonicBraid = client.holonicBraid || new HolonicBraidModule(http);
  client.holonicMemory = client.holonicMemory || new HolonicMemoryModule(http);
  client.images = client.images || new ImagesModule(http);
  client.orchestrator = client.orchestrator || new OrchestratorModule(http);
  client.reasoningNetwork = client.reasoningNetwork || new ReasoningNetworkModule(http);
  client.did = client.did || new DidModule(http);
  client.externalMemory = client.externalMemory || new ExternalMemoryModule(http);
  client.mLNet = client.mLNet || new MLNetModule(http);
  client.telemetry = client.telemetry || new TelemetryModule(http);
  client.usage = client.usage || new UsageModule(http);
  client.providers = client.providers || new ProvidersModule(http);
  client.a2A = client.a2A || new A2AModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
