'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { AdminModule } = require('./Admin');
const { AsyncApiModule } = require('./AsyncApi');
const { A2AModule } = require('./A2A');
const { BatchModule } = require('./Batch');
const { ClassificationModule } = require('./Classification');
const { CodeModule } = require('./Code');
const { CompletionModule } = require('./Completion');
const { ContextModule } = require('./Context');
const { DidModule } = require('./Did');
const { DiscoveryModule } = require('./Discovery');
const { DocumentsModule } = require('./Documents');
const { EmbeddingModule } = require('./Embedding');
const { EstimateModule } = require('./Estimate');
const { ExternalMemoryModule } = require('./ExternalMemory');
const { ExtractionModule } = require('./Extraction');
const { FahrnSolveModule } = require('./FahrnSolve');
const { FinetuningModule } = require('./Finetuning');
const { GraphRAGModule } = require('./GraphRAG');
const { GuardrailsModule } = require('./Guardrails');
const { HealthModule } = require('./Health');
const { HolonicBraidModule } = require('./HolonicBraid');
const { HolonicMemoryModule } = require('./HolonicMemory');
const { ImagesModule } = require('./Images');
const { KeysModule } = require('./Keys');
const { MemoryModule } = require('./Memory');
const { MLNetModule } = require('./MLNet');
const { ModerationModule } = require('./Moderation');
const { ModelsModule } = require('./Models');
const { OpenAICompatModule } = require('./OpenAICompat');
const { OrchestratorModule } = require('./Orchestrator');
const { OrchestrateModule } = require('./Orchestrate');
const { PromptModule } = require('./Prompt');
const { ProvidersModule } = require('./Providers');
const { ReasoningNetworkModule } = require('./ReasoningNetwork');
const { RerankModule } = require('./Rerank');
const { SearchModule } = require('./Search');
const { SpeechModule } = require('./Speech');
const { TelemetryModule } = require('./Telemetry');
const { TranslationModule } = require('./Translation');
const { UsageModule } = require('./Usage');
const { VideoModule } = require('./Video');
const { WebSocketSessionModule } = require('./WebSocketSession');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.admin = client.admin || new AdminModule(http);
  client.asyncApi = client.asyncApi || new AsyncApiModule(http);
  client.a2A = client.a2A || new A2AModule(http);
  client.batch = client.batch || new BatchModule(http);
  client.classification = client.classification || new ClassificationModule(http);
  client.code = client.code || new CodeModule(http);
  client.completion = client.completion || new CompletionModule(http);
  client.context = client.context || new ContextModule(http);
  client.did = client.did || new DidModule(http);
  client.discovery = client.discovery || new DiscoveryModule(http);
  client.documents = client.documents || new DocumentsModule(http);
  client.embedding = client.embedding || new EmbeddingModule(http);
  client.estimate = client.estimate || new EstimateModule(http);
  client.externalMemory = client.externalMemory || new ExternalMemoryModule(http);
  client.extraction = client.extraction || new ExtractionModule(http);
  client.fahrnSolve = client.fahrnSolve || new FahrnSolveModule(http);
  client.finetuning = client.finetuning || new FinetuningModule(http);
  client.graphRAG = client.graphRAG || new GraphRAGModule(http);
  client.guardrails = client.guardrails || new GuardrailsModule(http);
  client.health = client.health || new HealthModule(http);
  client.holonicBraid = client.holonicBraid || new HolonicBraidModule(http);
  client.holonicMemory = client.holonicMemory || new HolonicMemoryModule(http);
  client.images = client.images || new ImagesModule(http);
  client.keys = client.keys || new KeysModule(http);
  client.memory = client.memory || new MemoryModule(http);
  client.mLNet = client.mLNet || new MLNetModule(http);
  client.moderation = client.moderation || new ModerationModule(http);
  client.models = client.models || new ModelsModule(http);
  client.openAICompat = client.openAICompat || new OpenAICompatModule(http);
  client.orchestrator = client.orchestrator || new OrchestratorModule(http);
  client.orchestrate = client.orchestrate || new OrchestrateModule(http);
  client.prompt = client.prompt || new PromptModule(http);
  client.providers = client.providers || new ProvidersModule(http);
  client.reasoningNetwork = client.reasoningNetwork || new ReasoningNetworkModule(http);
  client.rerank = client.rerank || new RerankModule(http);
  client.search = client.search || new SearchModule(http);
  client.speech = client.speech || new SpeechModule(http);
  client.telemetry = client.telemetry || new TelemetryModule(http);
  client.translation = client.translation || new TranslationModule(http);
  client.usage = client.usage || new UsageModule(http);
  client.video = client.video || new VideoModule(http);
  client.webSocketSession = client.webSocketSession || new WebSocketSessionModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
