'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { CompletionModule } = require('./Completion');
const { HolonicBraidModule } = require('./HolonicBraid');
const { HolonicMemoryModule } = require('./HolonicMemory');
const { ImagesModule } = require('./Images');
const { OrchestratorModule } = require('./Orchestrator');
const { ReasoningNetworkModule } = require('./ReasoningNetwork');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.completion = client.completion || new CompletionModule(http);
  client.holonicBraid = client.holonicBraid || new HolonicBraidModule(http);
  client.holonicMemory = client.holonicMemory || new HolonicMemoryModule(http);
  client.images = client.images || new ImagesModule(http);
  client.orchestrator = client.orchestrator || new OrchestratorModule(http);
  client.reasoningNetwork = client.reasoningNetwork || new ReasoningNetworkModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
