'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/ml (source: WEB6 AI Layer WebAPI MLNetController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class MLNetModule {
  constructor(http) {
    this._http = http;

    // POST v1/ml/sentiment
    this.analyseSentiment = makeOperation(http, "v1/ml", "POST", "sentiment");
    // POST v1/ml/classify-task
    this.classifyTask = makeOperation(http, "v1/ml", "POST", "classify-task");
    // GET v1/ml/models
    this.listModels = makeOperation(http, "v1/ml", "GET", "models");
    // POST v1/ml/train
    this.trainTaskClassifier = makeOperation(http, "v1/ml", "POST", "train");
  }
}

module.exports = { MLNetModule };
