// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class MLNetModule {
  constructor(http: unknown);

  /** POST v1/ml/sentiment */
  analyseSentiment(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/ml/classify-task */
  classifyTask(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/ml/models */
  listModels(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/ml/train */
  trainTaskClassifier(args?: Record<string, any>): Promise<OASISResponse>;
}
