'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/models (source: WEB6 AI Layer WebAPI ModelCatalogueController.cs).
 * Browse the full WEB6 model catalogue — filter by plan, compare pricing, fetch details.
 */
class ModelsModule {
  constructor(http) {
    this._http = http;

    // GET v1/models  (pass { plan: "Free|Bronze|Silver|Gold" } to filter)
    this.list = makeOperation(http, "v1", "GET", "models");
    // GET v1/models/{modelId}
    this.get = makeOperation(http, "v1/models", "GET", "{modelId}");
  }
}

module.exports = { ModelsModule };
