// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class OrchestratorModule {
  constructor(http: unknown);

  /** GET v1/orchestrators/ */
  getAdapters(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/orchestrators/invoke */
  invoke(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/orchestrators/ */
  registerAdapter(args?: Record<string, any>): Promise<OASISResponse>;
}
