'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/orchestrators (source: WEB6 AI Layer WebAPI OrchestratorController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class OrchestratorModule {
  constructor(http) {
    this._http = http;

    // GET v1/orchestrators/
    this.getAdapters = makeOperation(http, "v1/orchestrators", "GET", "");
    // POST v1/orchestrators/invoke
    this.invoke = makeOperation(http, "v1/orchestrators", "POST", "invoke");
    // POST v1/orchestrators/
    this.registerAdapter = makeOperation(http, "v1/orchestrators", "POST", "");
  }
}

module.exports = { OrchestratorModule };
