'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/providers (source: WEB6 AI Layer WebAPI ProvidersController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ProvidersModule {
  constructor(http) {
    this._http = http;

    // GET v1/providers/status
    this.status = makeOperation(http, "v1/providers", "GET", "status");
  }
}

module.exports = { ProvidersModule };
