// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ProvidersModule {
  constructor(http: unknown);

  /** GET v1/providers/status */
  status(args?: Record<string, any>): Promise<OASISResponse>;
}
