// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ReasoningNetworkModule {
  constructor(http: unknown);

  /** POST v1/reasoning-network/dispatch */
  dispatch(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/reasoning-network/agents */
  getAgents(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/reasoning-network/agents */
  registerAgent(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/reasoning-network/agents/seed-openserv */
  seedOpenServAgents(args?: Record<string, any>): Promise<OASISResponse>;
}
