'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/reasoning-network (source: WEB6 AI Layer WebAPI ReasoningNetworkController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ReasoningNetworkModule {
  constructor(http) {
    this._http = http;

    // POST v1/reasoning-network/dispatch
    this.dispatch = makeOperation(http, "v1/reasoning-network", "POST", "dispatch");
    // GET v1/reasoning-network/agents
    this.getAgents = makeOperation(http, "v1/reasoning-network", "GET", "agents");
    // POST v1/reasoning-network/agents
    this.registerAgent = makeOperation(http, "v1/reasoning-network", "POST", "agents");
    // POST v1/reasoning-network/agents/seed-openserv
    this.seedOpenServAgents = makeOperation(http, "v1/reasoning-network", "POST", "agents/seed-openserv");
    // GET v1/reasoning-network/agents/{agentId}/skills/{category}
    this.getAgentSkills = makeOperation(http, "v1/reasoning-network", "GET", "agents/{agentId}/skills/{category}");
    // POST v1/reasoning-network/agents/{agentId}/skills/{category}/evolve
    this.evolveAgentSkill = makeOperation(http, "v1/reasoning-network", "POST", "agents/{agentId}/skills/{category}/evolve");
  }
}

module.exports = { ReasoningNetworkModule };
