// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class TelemetryModule {
  constructor(http: unknown);

  /** GET v1/telemetry/history */
  history(args?: Record<string, any>): Promise<OASISResponse>;
}
