'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/telemetry (source: WEB6 AI Layer WebAPI TelemetryController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class TelemetryModule {
  constructor(http) {
    this._http = http;

    // GET v1/telemetry/history
    this.history = makeOperation(http, "v1/telemetry", "GET", "history");
  }
}

module.exports = { TelemetryModule };
