// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class UsageModule {
  constructor(http: unknown);

  /** GET v1/usage/ */
  getUsage(args?: Record<string, any>): Promise<OASISResponse>;
}
